version: "3.3"
services:
  app:
    image: node:12.19.0
    restart: always
    working_dir: /app
    command: bash -c "yarn && yarn dev"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
